### ISSUE TITLE
Variables min_score and max_score

### ISSUE THREAD

**Issue by OmnesRes** [katherinemwood/corvids#1]
In line 565 of RecreateData.py, I think min_score and max_score should be self.min_score and self.max_score.

**Comment by katherinemwood** [comment]
It doesn't affect the functionality, but we'll make a note to correct it in a future release. Thanks.

**Comment by OmnesRes** [comment]
When I run the script it prompts me to enter min and max values.  When I then create a new object, like with this: rd = RecreateData(min_score=1, max_score=7, num_samples=20, mean=4, variance=2)
and run:
rd.recreateData()

It uses the min and max values I was originally prompted to give.  If other users use the script as I have, this could lead to erroneous results for them.

**Comment by katherinemwood** [comment]
Alright, we'll check this out and update it in the next release.

**Comment by katherinemwood** [comment]
We'll make this more transparent in an update, but just to clarify: the RecreateData class is meant to be used as an API, rather than a standalone script; that is, external scripts should call the objects and methods defined in the code. Running the script outright triggers a debug/test case, which is what you ran into.

**Comment by OmnesRes** [comment]
Ah yes, it makes sense to import the script rather than just run it.  But even here the user will run into a problem since min_score and max_score are never defined.
![image](https://user-images.githubusercontent.com/13816290/35703300-96c495c8-0769-11e8-8100-ba9b8398b0fa.png)

**Comment by sean-wilner** [comment]
Newest version has that fixed (both compiled and source) as well as another fix to a bug that cropped up when the code was run in single processing mode with "find first only" enabled (another issue that doesn't show up in the GUI).  Please do let us know if there are any more issues you run into.

**Comment by sean-wilner** [comment]
Scratch that, found one more instance of min_score erroneously sitting bare.  Have fixed it in the source, but the compiled version is not yet updated.

**Comment by sean-wilner** [comment]
Now supported in the compiled version.
