### ISSUE TITLE
CORVIDS v2

### ISSUE THREAD

**Issue by OmnesRes** [katherinemwood/corvids#3]
If the mean precision or variance precision is not set to 0, then line 702 of RecreateData.py throws an error. self.validMeansVariances() needs two arguments.  This is solved by: self.validMeansVariances(find_first), however then a new bug pops up.

The new validMeansVariances function no longer supports this:
means_list, variances_list = self.validMeansVariances()

Instead, it should be this:
mean_variance_pairs = self.validMeansVariances(find_first)

In addition, once that is fixed then the block of code below needs to be deleted.

Also, when find_first is set to True, it only prints a solution if debug is on, and then tries to run the rest of the code and inevitably throws an error.

**Comment by OmnesRes** [comment]
After fixing the code, I am running into an infinite loop with this call:
rd = RecreateData(min_score=1, max_score=7, num_samples=56, mean=4.27, variance=3.15,mean_precision=.005,variance_precision=.005,debug=False)
rd.recreateData(multiprocess=False,find_first=False)

**Comment by sean-wilner** [comment]
Hi Jordan,

Sorry I've been incommunicado, I'll get to this early tomorrow and hopefully have a fix for you by COB.

**Comment by OmnesRes** [comment]
No problem, I have CORVIDS 2.0 working, but I didn't explore what happened with the parameters that caused the infinite loop.  The code got stuck in finding the mean/variance pairs, and if I had to guess I would say it might be a floating point issue since that can happen at multiples of 8 for the sample size.

**Comment by sean-wilner** [comment]
So, I'm working through it right now, but the main issue is that the recreateData() call is all but deprecated and all calls we make to it through the GUI are broken apart to allow for mid run print statements to make it past Python's GIL.

I'll try to get this sorted this afternoon, but if you run into any problems with the broken apart recreateData calls or with the GUI run of things, please do let us know in the meantime!

**Comment by sean-wilner** [comment]
Okay, I've got a fix for it, and everything should work now from the single API call instead of the broken apart ones.
